### ISSUE TITLE
Admin actions on comments

### ISSUE THREAD

**Issue by miltontony** [praekelt/jmbo-comments#2]
https://github.com/praekelt/jmbo-comments/blob/develop/jmbocomments/admin.py#L5-L12

@smn 

These haven't been implemented. I'm worried about how moderators are currently moderating. Without bulk-select/flag, it's really difficult to moderate 1000 comments per day.

Not sure I completely understand how to implement these actions? Can you give some insight/sample code?

**Comment by smn** [comment]
\o/
